### ISSUE TITLE
Please provide a minimum php version 

### ISSUE THREAD

**Issue by drnkwati** [eldadfux/mailgun-php-lite#1]
Recommending Php 7 is a bad idea and will discourage people using older php versions from using this package. Please specify the minimum Php version required

**Comment by eldadfux** [comment]
I have mention both in composer.json and in the readme file that the required (not recommended) version is PHP 7+. This is because I have used scalar type declarations which are only available at PHP 7 and up. 

Anyone really needs to use this library on older PHP versions can easily fork it and remove the scalar type declarations for compatibility.

I really do believe the best option is to upgrade to PHP 7 which has many great new features, security updates and huge performance boost. I understand this might sometimes be hard but there are some tools that can help make it much easier and it will definitely be worth it.
